## np.newaxis :: adding an extra dimension

Effect of np.newaxis when we use it as indexing

In [23]:
import numpy as np
row = np.array([0,1,2])
row_vert = row[:, np.newaxis]
row_vert_vert = row_vert[:, np.newaxis]
row_vert_vert

array([[[0]],

       [[1]],

       [[2]]])

In [37]:
row.shape, row.ndim

((3,), 1)

In [38]:
row_vert.shape, row_vert.ndim

((3, 1), 2)

In [40]:
row_vert_vert.shape, row_vert_vert.ndim

((3, 1, 1), 3)

In [2]:
mask= np.array([1, 0, 1, 0], dtype = bool)
mask 

array([ True, False,  True, False])

In [7]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a[row_vert]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[]